### ISSUE TITLE
Checked status not applying to new elements

### ISSUE THREAD

**Issue by tchapuis** [tchapuis/simple-todo#2]
When you add a new element to the list, the checkbox doesn't mark the element as done (text striked out)

**Comment by Sixtinebs** [comment]
Do you have any idea where this bug came from?

**Comment by tchapuis** [comment]
I think the problem is that the event listener for marking items as done is not applied on new elements. The event listener is setting up only once on page loading.

**Comment by Sixtinebs** [comment]
Ok I try to fix that :)
